# Generated by Django 5.0.4 on 2024-04-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name of Category')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Level of Event')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name of Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Event')),
                ('pre_description', models.CharField(max_length=100, verbose_name='Pre description of Event')),
                ('description', models.TextField(verbose_name='Description of Event')),
                ('date', models.DateField(verbose_name='Date of Event')),
                ('photo', models.ImageField(default='/photo/2024/04/06/empty.png', upload_to='photo/%Y/%m/%d/', verbose_name='Image of Event')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Category')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.level', verbose_name='Level')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.organization', verbose_name='Organization')),
            ],
        ),
    ]
